# adding TINYGOROOT=/Users/zzq/.tinygo
set -g -x TINYGOROOT "/Users/zzq/.tinygo"
# updating PATH=/Users/zzq/.asdf/plugins/python/shims:/Users/zzq/.asdf/installs/python/3.10.5/bin:/Users/zzq/.asdf/shims:/Users/zzq/.asdf/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin/:/Users/zzq/.wasmer/bin:/Volumes/Store/.asdf/installs/emsdk/3.1.30:/Volumes/Store/.asdf/installs/emsdk/3.1.30/upstream/emscripten:/Volumes/Store/.asdf/installs/emsdk/3.1.30/node/14.18.2_64bit/bin:/Users/zzq/.tinygo/bin:/Users/zzq/bin:/opt/local/bin:/usr/local/bin:/opt/local/sbin:/usr/local/sbin:/Users/zzq/.pnpm:/Users/zzq/.deno/bin:/Users/zzq/.basher/bin:/Users/zzq/.sdkbox/bin:/usr/local/opt/make/libexec/gnubin:/Volumes/SOFT/Android/sdk/platform-tools:/Users/zzq/.arkade/bin:/Users/zzq/.golang/bin:/Users/zzq/.asdf/installs/python/3.10.5/bin:/Users/zzq/.wasmer/bin:/opt/local/share/luarocks/bin:/Users/zzq/.asdf/installs/lua/5.1.5/bin:/Users/zzq/.asdf/installs/lua/5.1.5/luarocks/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/zzq/.luarocks/bin:/Users/zzq/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/zzq/.wasmer/globals/wapm_packages/.bin:/Users/zzq/.wasmer/globals/wapm_packages/.bin -> /Users/zzq/.wasmer/bin:/Users/zzq/.tinygo/bin:/Users/zzq/bin:/opt/local/bin:/usr/local/bin:/opt/local/sbin:/usr/local/sbin:/Users/zzq/.pnpm:/Users/zzq/.deno/bin:/Users/zzq/.basher/bin:/Users/zzq/.sdkbox/bin:/usr/local/opt/make/libexec/gnubin:/Volumes/SOFT/Android/sdk/platform-tools:/Users/zzq/.arkade/bin:/Users/zzq/.golang/bin:/Users/zzq/.asdf/plugins/python/shims:/Users/zzq/.asdf/installs/python/3.10.5/bin:/Users/zzq/.asdf/shims:/Users/zzq/.asdf/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin/:/Users/zzq/.wasmer/bin:/Volumes/Store/.asdf/installs/emsdk/3.1.30:/Volumes/Store/.asdf/installs/emsdk/3.1.30/upstream/emscripten:/Volumes/Store/.asdf/installs/emsdk/3.1.30/node/14.18.2_64bit/bin:/opt/local/share/luarocks/bin:/Users/zzq/.asdf/installs/lua/5.1.5/bin:/Users/zzq/.asdf/installs/lua/5.1.5/luarocks/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/zzq/.luarocks/bin:/Users/zzq/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/zzq/.wasmer/globals/wapm_packages/.bin:/Users/zzq/.wasmer/globals/wapm_packages/.bin
set -g -x PATH "/Users/zzq/.wasmer/bin" "/Users/zzq/.tinygo/bin" "/Users/zzq/bin" "/opt/local/bin" "/usr/local/bin" "/opt/local/sbin" "/usr/local/sbin" "/Users/zzq/.pnpm" "/Users/zzq/.deno/bin" "/Users/zzq/.basher/bin" "/Users/zzq/.sdkbox/bin" "/usr/local/opt/make/libexec/gnubin" "/Volumes/SOFT/Android/sdk/platform-tools" "/Users/zzq/.arkade/bin" "/Users/zzq/.golang/bin" "/Users/zzq/.asdf/plugins/python/shims" "/Users/zzq/.asdf/installs/python/3.10.5/bin" "/Users/zzq/.asdf/shims" "/Users/zzq/.asdf/bin" "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/" "/Users/zzq/.wasmer/bin" "/Volumes/Store/.asdf/installs/emsdk/3.1.30" "/Volumes/Store/.asdf/installs/emsdk/3.1.30/upstream/emscripten" "/Volumes/Store/.asdf/installs/emsdk/3.1.30/node/14.18.2_64bit/bin" "/opt/local/share/luarocks/bin" "/Users/zzq/.asdf/installs/lua/5.1.5/bin" "/Users/zzq/.asdf/installs/lua/5.1.5/luarocks/bin" "/System/Cryptexes/App/usr/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Library/Apple/usr/bin" "/Users/zzq/.luarocks/bin" "/Users/zzq/.cargo/bin" "/Applications/kitty.app/Contents/MacOS" "/Users/zzq/.wasmer/globals/wapm_packages/.bin" "/Users/zzq/.wasmer/globals/wapm_packages/.bin"
alias "acme.sh"='/Users/zzq/.acme.sh/acme.sh'
alias "emacs"='TERM=xterm-24bits emacs'
alias "ll"='ls -agl'
alias "ls"='exa --header --icons --git'
alias "ta"='tmux attach -t'
alias "tad"='tmux attach -d -t'
alias "tkss"='tmux kill-session -t'
alias "tksv"='tmux kill-server'
alias "tl"='tmux list-sessions'
alias "tpc"='curl cip.cc'
alias "ts"='tmux new-session -s'