[tools]
"aqua:gokcehan/lf" = "latest"
"aqua:noborus/ov" = "latest"
bat = "latest"
cargo-binstall = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helix = "latest"
jq = "latest"
node = "latest"
pi = "latest"
pnpm = "latest"
ripgrep = "latest"
tokei = "latest"
usql = "latest"
zellij = "latest"
zig = "latest"
zoxide = "latest"
