/Volumes/Store/fontawesome-pro
/Volumes/Store/fontawesome-pro/sprites
/Volumes/Store/fontawesome-pro
/Volumes/Store
/Volumes/Store/fontawesome-pro
/Volumes/Store
/Volumes/Store/fontawesome-pro/svgs
/Users/zzq/Private/magit-server/.
/Users/zzq/Private
/Users/zzq/Private/magit-server
/Users/zzq/.golang/pkg/
/Users/zzq/.golang/pkg/mod
/Users/zzq/.golang/pkg/mod/github.com
/Users/zzq/.golang/bin
/Users/zzq/Private/magit-server/.
/Users/zzq/Private/magit-server/public/img
/Users/zzq/Private/magit-server/public/img/svg
/Users/zzq/Private/magit-server/public/img
/Users/zzq/Private/magit-server/public
/Users/zzq/Private/magit-server
/Users/zzq/Private/magit-server/web_src/js
/Users/zzq/Private/magit-server/web_src
/Users/zzq/Private/magit-server
/Users/zzq/Private/magit-server/templates
/Users/zzq/Private/magit-server/templates/org
/Users/zzq/Private/magit-server/templates
/Users/zzq/Private/magit-server
/Users/zzq/Private/magit-server/web_src/js/locale/devops
/Users/zzq/Private/magit-server
/Users/zzq/Private/magit-server/.
/Users/zzq/.config/clifm/
